/**
 * Documentation Display - JIRA, Slack, Confluence tabs with copy functionality
 */
import React, { useState } from 'react';
import { FileText, MessageSquare, Book, Copy, CheckCircle2, ExternalLink } from 'lucide-react';

interface DocumentationDisplayProps {
  documentation: {
    jira?: any;
    slack?: any;
    confluence?: any;
  };
  incidentId: string;
}

const DocumentationDisplay: React.FC<DocumentationDisplayProps> = ({ documentation, incidentId }) => {
  const [activeTab, setActiveTab] = useState<'jira' | 'slack' | 'confluence'>('jira');
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopied(type);
    setTimeout(() => setCopied(null), 2000);
  };

  const tabs = [
    { id: 'jira' as const, label: 'JIRA', icon: FileText, color: 'text-blue-600 border-blue-500' },
    { id: 'slack' as const, label: 'Slack', icon: MessageSquare, color: 'text-purple-600 border-purple-500' },
    { id: 'confluence' as const, label: 'Confluence', icon: Book, color: 'text-green-600 border-green-500' },
  ];

  const getContent = () => {
    const doc = documentation[activeTab];
    if (!doc) return 'No documentation available';
    if (typeof doc === 'string') return doc;
    return doc.content || doc.description || doc.message || JSON.stringify(doc, null, 2);
  };

  const getTitle = () => {
    const doc = documentation[activeTab];
    return doc?.title || `${tabs.find(t => t.id === activeTab)?.label} - ${incidentId}`;
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-card overflow-hidden">
      <div className="px-6 py-4 border-b border-slate-200 bg-slate-50/50 flex items-center justify-between">
        <div>
          <h3 className="text-base font-bold text-slate-900">Automated Documentation</h3>
          <p className="text-xs text-slate-500 mt-0.5">Generated by Nova 2 Lite</p>
        </div>
        <span className="px-2.5 py-1 bg-violet-50 text-violet-700 text-[10px] font-bold rounded-full border border-violet-200">
          Nova 2 Lite
        </span>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-200 px-6">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-3 flex items-center gap-2 text-xs font-bold transition-colors border-b-2 -mb-px ${
                isActive ? tab.color : 'border-transparent text-slate-500 hover:text-slate-700'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Content */}
      <div className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h4 className="text-sm font-bold text-slate-900">{getTitle()}</h4>
          <button
            onClick={() => copyToClipboard(getContent(), activeTab)}
            className="px-3 py-1.5 text-xs text-slate-600 hover:text-slate-900 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors flex items-center gap-1.5 font-semibold"
          >
            {copied === activeTab ? (
              <><CheckCircle2 className="w-3 h-3 text-emerald-600" /> Copied!</>
            ) : (
              <><Copy className="w-3 h-3" /> Copy</>
            )}
          </button>
        </div>

        <div className="bg-slate-50 rounded-xl p-4 border border-slate-200 max-h-80 overflow-y-auto">
          <pre className="text-xs text-slate-700 whitespace-pre-wrap font-mono leading-relaxed">
            {getContent()}
          </pre>
        </div>

        <div className="flex gap-2 pt-4 mt-4 border-t border-slate-100">
          <button className="btn-nova px-4 py-2 bg-indigo-600 text-white rounded-lg text-xs font-bold flex items-center gap-1.5">
            <ExternalLink className="w-3.5 h-3.5" />
            Open in {tabs.find(t => t.id === activeTab)?.label}
          </button>
          <button className="px-4 py-2 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold hover:bg-slate-200 transition-colors">
            Export Markdown
          </button>
        </div>
      </div>
    </div>
  );
};

export default DocumentationDisplay;
