"""
Report API — PDF export with Nova Canvas cover

Generates PDF: Cover (Nova Canvas) → Executive Summary → Technical Details → Remediation → Compliance → Appendix
"""
import io
import base64
from fastapi import APIRouter, HTTPException, Body
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/api/report", tags=["report"])


class ExportPdfRequest(BaseModel):
    incident_id: str
    markdown: str
    cover_image_base64: Optional[str] = None


def _render_pdf(incident_id: str, markdown: str, cover_b64: Optional[str]) -> bytes:
    """Generate PDF using reportlab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        raise HTTPException(status_code=500, detail="reportlab not installed. Run: pip install reportlab")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
    styles = getSampleStyleSheet()
    story = []

    # Cover page
    cover_added = False
    if cover_b64:
        try:
            img_data = base64.b64decode(cover_b64.split(",")[-1] if "," in cover_b64 else cover_b64)
            img = Image(io.BytesIO(img_data), width=6 * inch, height=4 * inch)
            story.append(img)
            story.append(Spacer(1, 0.2 * inch))
            cover_added = True
        except Exception:
            pass

    # Text cover if no image or image failed
    if not cover_added:
        cover_style = ParagraphStyle(
            "Cover", parent=styles["Heading1"], fontSize=24, alignment=TA_CENTER, spaceAfter=12
        )
        story.append(Spacer(1, 2 * inch))
        story.append(Paragraph("Security Incident Report", cover_style))
        story.append(Paragraph(f"{incident_id}", ParagraphStyle("Sub", parent=styles["Normal"], fontSize=16, alignment=TA_CENTER)))
        story.append(Paragraph("Generated by Nova Sentinel", ParagraphStyle("Sub2", parent=styles["Normal"], fontSize=10, alignment=TA_CENTER, textColor="gray")))

    story.append(PageBreak())

    # Body: convert markdown to simple paragraphs (basic)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)
    for line in markdown.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.1 * inch))
            continue
        # Escape HTML for reportlab
        line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if line.startswith("# "):
            story.append(Paragraph(line[2:], styles["Heading1"]))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], styles["Heading2"]))
        elif line.startswith("### "):
            story.append(Paragraph(line[4:], styles["Heading3"]))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph("• " + line[2:], body_style))
        elif line.startswith("|"):
            # Simple table row - render as paragraph
            story.append(Paragraph(line.replace("|", " | "), ParagraphStyle("Table", parent=body_style, fontSize=9)))
        else:
            story.append(Paragraph(line, body_style))

    doc.build(story)
    return buffer.getvalue()


@router.post("/export-pdf")
async def export_pdf(req: ExportPdfRequest) -> StreamingResponse:
    """Generate and return PDF report."""
    try:
        pdf_bytes = _render_pdf(req.incident_id, req.markdown, req.cover_image_base64)
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="nova-sentinel-report-{req.incident_id}.pdf"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
